const measures={
  length:{
    show:{zh:'长度',},
    units:{
      m:{
        show:{zh:'米'},
      },
      cm:{
        show:{zh:'厘米'},
        a:0.01,
      },
      mm:{
        show:{zh:'毫米'},
        a:0.001,
      },
      km:{
        show:{zh:'千米'},
        a:1000,
      },
      dm:{
        show:{zh:'分米'},
        a:0.1,
      },
    }
  },
  mass:{
    show:{zh:'质量'},
    units: {
      kg: {
        show: {zh: '千克'},
      },
      g: {
        show: {zh: '克'},
        a: 0.001,
      },
      mg: {
        show: {zh: '毫克'},
        a: 0.000001,
      },
      t: {
        show: {zh: '吨'},
        a: 1000,
      },
      ug:{
        sign:'μg',
        show: {zh: '微克'},
        a: 0.000000001,
      }
    }
  },
  time:{
    show:{zh:'时间'},
    units:{
      s:{
        show:{zh:'秒'},
      },
      m:{
        show:{zh:'分钟'},
        a:60,
      },
      h:{
        show:{zh:'时'},
        a:3600,
      },
      d:{
        show:{zh:'天'},
        a:86400,
      },
      ms:{
        show:{zh:'毫秒'},
        a:0.001,
      }
    }
  },
  current:{
    show:{zh:'电流'},
    units:{
      A:{
        show:{zh:'安培'}
      },
      mA:{
        show:{zh:'毫安'},
        a:0.001
      }
    }
  },
  temperature:{
    show:{zh:'温度'},
    units:{
      C:{
        sign:'℃',
        show:{zh:'摄氏度'},
        a:1,
        b:273.15
      },
      F:{
        sign:'℉',
        show:{zh:'华氏度'},
        a:5/9,
        b:2298.35/9
      },
      K:{
        show:{zh:'开尔文'},
      },
    }
  },
  area:{
    show:{zh:'面积'},
    combx:{
      length:2
    },
    units:{
      m2:{
        sign:'m\u00b2',
        show:{zh:'平方米'}
      },
      cm2:{
        sign:'cm\u00b2',
        show:{zh:'平方厘米'},
        combx:{
          length_cm:2
        }
      },
      km2:{
        sign:'Km\u00b2',
        show:{zh:'平方千米'},
        combx:{
          length_km:2
        }
      },
      mu:{
        show:{zh:'亩'},
        a:2000/3,
      },
      hm2:{
        sign:'hm\u00b2',
        show:{zh:'公顷'},
        a:10000,
      }
    }
  },
  volume:{
    show:{
      zh:'体积',
    },
    combx:{
      length:3
    },
    units:{
      m3:{
        sign:'m\u00b3',
        show:{zh:'立方米'}
      },
      L:{
        show:{zh:'升'},
        combx:{
          length_dm:3
        }
      },
      mL:{
        show:{zh:'毫升'},
        combx:{
          length_cm:3
        }
      }
    }
  },
  force:{
    show:{zh:'力'},
    combx:{
      mass:1,
      length:1,
      time:-2
    },
    units:{
      N:{
        show:{zh:'牛'},
        combx:{
          mass_kg:1,
          length_m:1,
          time_s:-2
        },
      }
    }
  },
  energy:{
    show:{zh:'能量'},
    combx:{
      force:1,
      length:1
    },
    units:{
      J:{
        combx:{
          force_N:1,
          length_m:1
        },
        show:{zh:'焦耳'}
      },
      'KWh':{
        show:{zh:'千瓦时'},
        combx:{
          power_kW:1,
          time_h:1
        }
      }
    },
  },
  power:{
    show:{zh:'功率'},
    combx:{
      energy:1,
      time:-1
    },
    units:{
      W:{
        show:{zh:'瓦'}
      },
      kW:{
        show:{zh:'千瓦'},
        a:1000
      }
    }
  },
  pressure:{
    show:{
      zh:'压强'
    },
    combx:{
      force:1,
      area:-1
    },
    units:{
      Pa:{
        show:{
          zh:'帕'
        }
      },
      kPa:{
        show:{
          zh:'千帕'
        },
        a:1000
      },
      MPa:{
        show:{
          zh:'兆帕'
        },
        a:1000000
      },
      atm:{
        show:{
          zh:'大气压'
        },
        a:101325
      },
      mmHg:{
        show:{
          zh:'毫米汞柱'
        },
        a:133.3223684
      }
    }
  },
  density:{
    show:{zh:'密度/质量浓度'},
    combx:{
      mass:1,
      volume:-1
    },
    units:{
      'Kg/m3':{
        sign:'Kg/m\u00b3',
        show:{zh:'千克每立方米'}
      },
      'g/L':{
        show:{zh:'克每升'}
      },
      'mg/L':{
        show:{zh:'毫克每升'},
        combx:{
          mass_mg:1,
          volume_L:-1
        }
      },
      'ug/L':{
        sign:'μg/L',
        show:{zh:'微克每升'},
        combx:{
          mass_ug:1,
          volume_L:-1
        }
      },
      'ppm':{
        sign:'μg/L',
        show:{zh:'微克每升'},
        combx:{
          mass_ug:1,
          volume_L:-1
        }
      }
    }
  },
  flowVolume:{
    show:{zh:'体积流量'},
    combx:{
      volume:1,
      time:-1
    },
    units:{
      'm3/s':{
        sign:'m\u00b3/s',
        show:{zh:'立方米每秒'}
      },
      'm3/h':{
        sign:'m\u00b3/h',
        show:{zh:'立方米每小时'},
        combx:{
          time_h:-1
        },
      },
    }
  },
  voltage:{
    show:{zh:'电压'},
    combx:{
      power:1,
      current:-1
    },
    units:{
      V:{
        show:{zh:'伏'}
      },
      KV:{
        show:{zh:'千伏'},
        a:1000
      }
    }
  },
  PH:{
    show:{zh:'酸碱度'},
    units:{
      PH:{
        show:{zh:'PH'}
      }
    }
  },
  boolean:{
    show:{zh:'开关/启停状态'},
    units:{
      bool:{
        show:{zh:'布尔量'}
      },
      open0:{
        show:{zh:'0启动'},
        a:-1,
        b:1
      },
      open1:{
        show:{zh:'1启动'}
      }
    }
  }
};

module.exports=measures;