const measures={
  length:{
    show:{zh:'长度',},
    units:{
      m:{
        show:{zh:'米'},
      },
      cm:{
        show:{zh:'厘米'},
        a:0.01,
      },
      mm:{
        show:{zh:'毫米'},
        a:0.001,
      },
      km:{
        show:{zh:'千米'},
        a:1000,
      },
      dm:{
        show:{zh:'分米'},
        a:0.1,
      },
      um:{
        show:{zh:'微米'},
        a:0.000001,
      },
    }
  },
  mass:{
    show:{zh:'质量'},
    units: {
      kg: {
        show: {zh: '千克'},
      },
      g: {
        show: {zh: '克'},
        a: 0.001,
      },
      mg: {
        show: {zh: '毫克'},
        a: 0.000001,
      },
      t: {
        show: {zh: '吨'},
        a: 1000,
      },
      ug:{
        sign:'μg',
        show: {zh: '微克'},
        a: 0.000000001,
      }
    }
  },
  time:{
    show:{zh:'时间'},
    units:{
      s:{
        show:{zh:'秒'},
      },
      m:{
        show:{zh:'分钟'},
        a:60,
      },
      h:{
        show:{zh:'时'},
        a:3600,
      },
      d:{
        show:{zh:'天'},
        a:86400,
      },
      ms:{
        show:{zh:'毫秒'},
        a:0.001,
      }
    }
  },
  voltage:{
    show:{zh:'电压'},
    combx:{
      power:1,
      current:-1
    },
    units:{
      V:{
        show:{zh:'伏'}
      },
      mV:{
        show:{zh:'毫伏'},
        a:0.001
      },
      kV:{
        show:{zh:'千伏'},
        a:1000
      }
    }
  },
  current:{
    show:{zh:'电流'},
    units:{
      A:{
        show:{zh:'安培'}
      },
      mA:{
        show:{zh:'毫安'},
        a:0.001
      }
    }
  },
  speed:{
    show:{zh:'速度'},
    combx:{
      length:1,
      time:-1
    },
    units:{
      'm/s':{
        show:{zh:'米每秒'}
      },
      'km/h':{
        show:{zh:'千米每小时'},
        combx:{
          length_km: 1,
          time_h:-1
        }
      },
      'mm/s':{
        show:{zh:'毫米每秒'},
        combx:{
          length_mm: 1,
          time_s:-1
        }
      },
    },
  },
  temperature:{
    show:{zh:'温度'},
    units:{
      C:{
        sign:'℃',
        show:{zh:'摄氏度'},
        a:1,
        b:273.15
      },
      F:{
        sign:'℉',
        show:{zh:'华氏度'},
        a:5/9,
        b:2298.35/9
      },
      K:{
        show:{zh:'开尔文'},
      },
    }
  },
  area:{
    show:{zh:'面积'},
    combx:{
      length:2
    },
    units:{
      m2:{
        sign:'m\u00b2',
        show:{zh:'平方米'}
      },
      cm2:{
        sign:'cm\u00b2',
        show:{zh:'平方厘米'},
        combx:{
          length_cm:2
        }
      },
      km2:{
        sign:'km\u00b2',
        show:{zh:'平方千米'},
        combx:{
          length_km:2
        }
      },
      mu:{
        show:{zh:'亩'},
        a:2000/3,
      },
      hm2:{
        sign:'hm\u00b2',
        show:{zh:'公顷'},
        a:10000,
      }
    }
  },
  volume:{
    show:{
      zh:'体积',
    },
    combx:{
      length:3
    },
    units:{
      m3:{
        sign:'m\u00b3',
        show:{zh:'立方米'}
      },
      L:{
        show:{zh:'升'},
        combx:{
          length_dm:3
        }
      },
      mL:{
        show:{zh:'毫升'},
        combx:{
          length_cm:3
        }
      }
    }
  },
  force:{
    show:{zh:'力'},
    combx:{
      mass:1,
      length:1,
      time:-2
    },
    units:{
      N:{
        show:{zh:'牛'},
      },
      kgf:{
        show:{zh:'千克力'},
        a:9.80665
      }
    }
  },
  energy:{
    show:{zh:'能量'},
    combx:{
      force:1,
      length:1
    },
    units:{
      J:{
        combx:{
          force_N:1,
          length_m:1
        },
        show:{zh:'焦耳'}
      },
      'kWh':{
        show:{zh:'千瓦时'},
        combx:{
          power_kW:1,
          time_h:1
        }
      }
    },
  },
  power:{
    show:{zh:'功率'},
    combx:{
      energy:1,
      time:-1
    },
    units:{
      W:{
        show:{zh:'瓦'}
      },
      kW:{
        show:{zh:'千瓦'},
        a:1000
      }
    }
  },
  pressure:{
    show:{
      zh:'压强'
    },
    combx:{
      force:1,
      area:-1
    },
    units:{
      Pa:{
        show:{
          zh:'帕'
        }
      },
      kPa:{
        show:{
          zh:'千帕'
        },
        a:1000
      },
      MPa:{
        show:{
          zh:'兆帕'
        },
        a:1000000
      },
      atm:{
        show:{
          zh:'大气压'
        },
        a:101325
      },
      mmHg:{
        show:{
          zh:'毫米汞柱'
        },
        a:133.3223684
      },
      bar:{
        show:{
          zh:'巴'
        },
        a:100000
      },
      mbar:{
        show:{
          zh:'毫巴'
        },
        a:100
      },
      'kgf/cm2':{
        show:{
          zh:'千克力每平方厘米'
        },
        sign:'kgf/cm\u00b2',
        combx:{
          force_kgf:1,
          area_cm2:-1
        }
      },
      'kgf/m2':{
        show:{
          zh:'千克力每平方米'
        },
        sign:'kgf/m\u00b2',
        combx:{
          force_kgf:1,
          area_m2:-1
        }
      },
    }
  },
  density:{
    show:{zh:'密度/质量浓度'},
    combx:{
      mass:1,
      volume:-1
    },
    units:{
      'kg/m3':{
        sign:'kg/m\u00b3',
        show:{zh:'千克每立方米'}
      },
      'g/L':{
        show:{zh:'克每升'}
      },
      'mg/L':{
        show:{zh:'毫克每升'},
        combx:{
          mass_mg:1,
          volume_L:-1
        }
      },
      'ug/L':{
        sign:'μg/L',
        show:{zh:'微克每升'},
        combx:{
          mass_ug:1,
          volume_L:-1
        }
      },
      'ppm':{
        sign:'μg/L',
        show:{zh:'微克每升'},
        combx:{
          mass_ug:1,
          volume_L:-1
        }
      }
    }
  },
  flowVolume:{
    show:{zh:'体积流量'},
    combx:{
      volume:1,
      time:-1
    },
    units:{
      'm3/s':{
        sign:'m\u00b3/s',
        show:{zh:'立方米每秒'}
      },
      'm3/h':{
        sign:'m\u00b3/h',
        show:{zh:'立方米每小时'},
        combx:{
          time_h:-1
        },
      },
    }
  },
  flowMass:{
    show:{zh:'质量流量'},
    combx:{
      mass:1,
      time:-1
    },
    units: {
      'kg/s': {
        show: {zh: '千克每秒'}
      },
      'kg/h': {
        show: {zh: '千克每小时'},
        combx:{
          time_h:-1
        }
      },
      't/h': {
        show: {zh: '吨每小时'},
        combx:{
          mass_t:1,
          time_h:-1
        }
      },
    }
  },
  degree:{
    show:{zh:'角度'},
    units:{
      rad:{
        show:{zh:'弧度'},
      },
      deg:{
        show:{zh:'角度'},
        a:Math.PI/180
      },
      turn:{
        show:{zh:'转'},
        a:Math.PI*2
      },
    }
  },
  speedDegree:{
    show:{zh:'转速/角速度'},
    combx:{
      degree:1,
      time:-1
    },
    units:{
      'rad/s':{
        show:{zh:'弧度每秒'}
      },
      'RPM':{
        show:{zh:'转每分钟'},
        combx:{
          degree_turn:1,
          time_m:-1
        }
      }
    }
  },
  PH:{
    show:{zh:'酸碱度'},
    units:{
      PH:{
        show:{zh:'PH'}
      }
    }
  },
  boolean:{
    show:{zh:'开关/启停状态'},
    units:{
      bool:{
        show:{zh:'布尔量'}
      }
    }
  },
  multiple:{
    show:{zh:'倍率'},
    units:{
      pc:{
        show:{zh:'百分数'},
        sign:'%',
        a:0.01
      },
      pm:{
        show:{zh:'千分数'},
        sign:'‰',
        a:0.001
      },
    }
  },
  resistance:{
    show:{zh:'电阻'},
    combx:{
      voltage:1,
      current:-1
    },
    units:{
      Ohm:{
        show:{zh:'欧姆'},
        sign:'Ω'
      },
      kOhm:{
        show:{zh:'千欧姆'},
        sign:'kΩ',
        a:1e3
      },
      MOhm:{
        show:{zh:'兆欧姆'},
        sign:'MΩ',
        a:1e6
      },
    }
  },
  frequency:{
    show:{zh:'频率'},
    combx:{
      time:-1
    },
    units:{
      Hz:{
        show:{zh:'赫兹'}
      },
      kHz:{
        show:{zh:'千赫兹'},
        a:1e3
      },
      MHz:{
        show:{zh:'兆赫兹'},
        a:1e6
      },
    }
  }
};

module.exports=measures;